name: "Terraform CD Workflow"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  
jobs:
  Terraform-Workflow :
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Verify Azure Login
        run: az account show

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init 
        run: terraform init
        working-directory: ./terraform_infra

      - name: Terraform Apply 
        run: terraform apply --auto-approve
        working-directory: ./terraform_infra
